version: "3"

# Elastic Beanstalk has wholly inadequate support for
# secrets.
# # "file" secrets are read from your host-side
# # working directory when you run `docker compose up`.
# secrets:
#   admin.username:
#     file: .docker_compose_secrets/admin.username
#   admin.password:
#     file: .docker_compose_secrets/admin.password
#   jwt.access.token.secret:
#     file: .docker_compose_secrets/jwt.access.token.secret
#   jwt.access.token.duration:
#     file: .docker_compose_secrets/jwt.access.token.duration

services:
  intake_server:
    build: .

    ports:
      - 80:8000 # outside:inside container

    environment:
      # Expect to find these in, e.g., .env
      - admin.username
      - admin.password
      - jwt.access.token.secret
      - jwt.access.token.duration
    # secrets:
    #   - admin.username
    #   - admin.password
    #   - jwt.access.token.secret
    #   - jwt.access.token.duration
