version: "3"

# Elastic Beanstalk has wholly inadequate support for
# secrets.
# # "file" secrets are read from your host-side
# # working directory when you run `docker compose up`.
# secrets:
#   ADMIN_USERNAME:
#     file: .docker_compose_secrets/ADMIN_USERNAME
#   ADMIN_PASSWORD:
#     file: .docker_compose_secrets/ADMIN_PASSWORD
#   JWT_ACCESS_SECRET:
#     file: .docker_compose_secrets/JWT_ACCESS_SECRET
#   JWT_ACCESS_DURATION:
#     file: .docker_compose_secrets/JWT_ACCESS_DURATION
#   USER_DB_PATH:
#     file: .docker_compose_secrets/USER_DB_PATH

services:
  web:
    image: nginx
    volumes:
      - ./nginx_config:/etc/nginx
    ports:
      - "80:80" # outside:inside container
  fnf_intake_server:
    build: .

    # Elastic beanstalk writes env vars to .env, but not to any 
    # other path.
    env_file: .env
